[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://vixcera.my.id"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Set-Cookie"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200